name: Eslint & Typescript compiler & Tests

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Fix up git URLs
        run: echo -e '[url "https://github.com/"]\n  insteadOf = "git://github.com/"' >> ~/.gitconfig
      - name: Checkout 🛎️
        uses: actions/checkout@v3.0.0
        with:
          persist-credentials: false
      - name: Install node modules
        run: yarn install
      - name: Run eslint
        run: yarn lint
      - name: Run TS compiler
        run: yarn tsc-compile
      - name: Run tests
        run: yarn test
